0xPolygon/polygon-edge-docs

- docs/how-tos/howto-query-operator.md
- docs/how-tos/howto-set-ibft.md
PR related to this - [link](https://github.com/0xPolygon/polygon-sdk/pull/61)
> Add flags where arguments are accepted

- docs/cli-commands.md
- docs/how-tos/howto-query-json-rpc.md
- docs/how-tos/howto-query-operator.md
- docs/how-tos/howto-set-ibft.md
This PR updates the commands in the documentation, following [PR #62](https://github.com/0xPolygon/polygon-sdk/pull/62).
> Update the commands, following PR #62 on the main repo

- docs/how-tos/howto-manage-private-keys.md
- sidebars.js
This PR adds documentation detailing the private key format used in the Polygon SDK.
> Add the documentation on private key management

- docs/cli-commands.mdx
- docs/how-tos/howto-setup-ibft/howto-set-ibft-on-the-cloud.md
Add docs related to `dns` flag and updated nat section
> added docs for dns support

- docs/cli-commands.mdx
- docs/how-tos/howto-run-loadbot.md
- sidebars.js
This PR includes the instructions for running the loadbot.
> Add loadbot documentation

- docs/cli-commands.mdx
- docs/how-tos/howto-setup-ibft/howto-set-ibft-locally.md
- docs/how-tos/howto-setup-ibft/howto-set-ibft-on-the-cloud.md
- docs/sample-config.md
- static/files/sampleConfig.md
In this PR, I have documented the process/commands to start PSDK node using config file
> Docs for config file

- docs/how-tos/howto-add-new-validators.md
- sidebars.js
Create documentation for how to add new validator nodes in active IBFT network.
> Add new validator node documentation

- docs/how-tos/howto-setup-ibft/howto-set-ibft-locally.md
- docs/how-tos/howto-setup-ibft/howto-set-ibft-on-the-cloud.md
This PR adds additional info on the usage of the `price-limit` flag.
Spawned out of the discussion in https://github.com/0xPolygon/polygon-sdk/discussions/281
> Add further docs for the price limit

- docs/cli-commands.mdx
This PR adds the description of `--json` flag which will be added in https://github.com/0xPolygon/polygon-sdk/pull/277
> Add description of --json flag

- docs/cli-commands.mdx
- docs/how-tos/howto-run-loadbot.md
This PR updated loadbot docs based on the changes made in [PR 283](https://github.com/0xPolygon/polygon-sdk/pull/283)
> updated loadbot docs

- docs/additional-features/stress-testing.md
This PR adds updated info for the loadbot docs.
> Update info for the loadbot

- docs/get-started/set-up-ibft-locally.md
- docs/get-started/set-up-ibft-on-the-cloud.md
Added info note on increasing the open files limit in order to avoid issues too many open files error.
> added instructions for rasing file descriptors limit

- docs/additional-features/stress-testing.md
- docs/get-started/cli-commands.mdx
This PR adds documentation for the new loadbot features.
PSDK PR:
https://github.com/0xPolygon/polygon-sdk/pull/329
> Add the docs for the new loadbot features

- docs/get-started/cli-commands.mdx
This PR adds support for missing TxPool subscribe flags.
Reference PR: https://github.com/0xPolygon/polygon-edge/pull/323
> Add support for TxPool subscribe flags

- docs/get-started/performance-reports.md
- docs/overview.md
- sidebars.js
- yarn.lock
Added the Performance Tests page to the docs.
Fixes EDGE-25
> TPS reports

- docs/consensus/migration-to-pos.md
- docs/consensus/pos-stake-unstake.md
- docs/get-started/cli-commands.mdx
- sidebars.js
Fixes EDGE-63
This PR adds description about PoA/PoS switch function, which will be added by https://github.com/0xPolygon/polygon-edge/pull/334
> Add description about PoA/PoS switch

- docs/get-started/cli-commands.mdx
This PR updates the changed flags resulting from https://github.com/0xPolygon/polygon-edge/pull/410
Fixes EDGE-44
> CLI Refactor

- docs/get-started/cli-commands.mdx
changed jsonrpc flag default address to 0.0.0.0
Fixes EDGE-421
> changed jsonrpc flag default address to 0.0.0.0

- docs/get-started/cli-commands.mdx
* add access-control-allow-origins flag
* add more description for jsonrpc flag
* add additional desc for prometheus flag
* move flag desc to appropriate sections
*  minor fixes
Fixes EDGE-436
> Add CORS flag, fix default descriptions, move server flag descriptions to proper section

- docs/additional-features/blockscout.md
- docs/get-started/set-up-blockscout.md
- sidebars.js
This PR adds the step-by-step instructions on how to compile and deploy a Blockscout instance.
Fixes EDGE-414
> Adding how to deploy Blockscout page

- .github/workflows/test.yaml
- __tests__/danglingPages_test.js
- babel.config.js
- package.json
- yarn.lock
Fixes EDGE-455
Description:
Adding unit test which checks is there any page that is not accessible from the sidebar. This unit test will be triggered on every pull request with GH action
> Add unit test for checking dangling pages

- docs/get-started/cli-commands.mdx
Fixes EDGE-6
This PR adds the documentation for the new flag : `max-validator-count`.
Related to [this PR](https://github.com/0xPolygon/polygon-edge/pull/397).
> Add documentation for pos genesis flag

- docs/configuration/enable-metrics.mdx
This PR updates newly added Prometheus metrics from https://github.com/0xPolygon/polygon-edge/pull/343
> Update newly added network metrics

- docs/architecture/modules/blockchain.md
`block := blocks[i]` & `header := block.Header` were not being used properly.
> improve readability of example codes in blockchain.md

- docs/get-started/json-rpc-commands.mdx
**Description:**
This PR adds documentation for eth_getFilterLogs JSON-RPC method + it fixes documentation for other eth filter methods. 
**PR**
https://github.com/0xPolygon/polygon-edge/pull/538
Fixes EDGE-548
> Add eth_getFilterLogs

- docs/configuration/sample-config.md
Rework of > https://github.com/0xPolygon/polygon-edge-docs/pull/69
> Improve server config file. Using TypeScript to describe it

- docs/get-started/cli-commands.mdx
Relevant: https://github.com/0xPolygon/polygon-edge/pull/582
This PR adds the description about `ibft-base-timeout` CLI arguments of server command
> Add description about ibft-base-timeout

- docs/get-started/json-rpc-commands.mdx
Added additional explanation for the changes to the `eth_getPrice` introduced in https://github.com/0xPolygon/polygon-edge/pull/590
> add additional info to eth_gasPrice
